DELIMITER $$
CREATE FUNCTION sayHello(humanName VARCHAR(100))
RETURNS VARCHAR(100) DETERMINISTIC
BEGIN
 RETURN  CONCAT("Hello: ", humanName);
END $$
DELIMITER ;

SELECT sayHello("Nacho");

DROP FUNCTION sayHello;